### ISSUE TITLE
compile on windows 

### ISSUE THREAD

**Issue by yylovess** [cvfish/PangaeaTracking#9]
Thank you for open your work and it is remarkable. I have try it on Windows 10, Visual Studio 2013. When I compile the MainEngine, I have some errors: " error C1083: can not open file: “hdf5.h”: No such file or directory". But I am sure I have linked the project to the directory where there is the file “hdf5.h”. Do you know what is the reason for this error?

Thank you very much.

**Comment by cvfish** [comment]
I think you need to install hdf5, https://support.hdfgroup.org/HDF5/

**Comment by yylovess** [comment]
Thank you but I have install hdf5
发自网易邮箱大师
On 04/20/2017 12:24, Rui Yu wrote: I think you need to install hdf5, https://support.hdfgroup.org/HDF5/

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cvfish/PangaeaTracking","title":"cvfish/PangaeaTracking","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cvfish/PangaeaTracking"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cvfish in #9: I think you need to install hdf5, https://support.hdfgroup.org/HDF5/"}],"action":{"name":"View Issue","url":"https://github.com/cvfish/PangaeaTracking/issues/9#issuecomment-295671108"}}}

**Comment by yylovess** [comment]
@cvfish Thank you. 
But I have installed hdf5 already, and linked the project to the directory where there is the file “hdf5.h”.  
The “hdf5.h” still can not be opened.
Have someone else also meet this problems? If so how thay can solve it?
Thank you very much.

**Comment by yylovess** [comment]
@cvfish Thank you very much ,and I have solved this problem. 
What I did is change the platform to x64. I will close this issue.
